### ISSUE TITLE
Running the command line get a bug and exit

### ISSUE THREAD

**Issue by LemassonLouis** [katalon-studio/kr-cli#13]
<details>
<summary>Environnement</summary>

* Windows 11 
* Node 14.21.3
* NPM 6.14.18
* kr-cli 1.1.0
* Katalon Recorder 5.9.0

</details>

## The issue

When I run the following command, I get the following error and the the programm exit without doing anything else.

```
kr-cli run chrome "C:\tests\loginpage.html" --report "C:\tests\kr-test"
```

![2024-02-02_10h15_09](https://github.com/katalon-studio/kr-cli/assets/144131578/c1a62dca-92d7-4681-bd20-e335216dda8b)

```
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9708) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9708) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:9708) UnhandledPromiseRejectionWarning: Error: Server was killed with SIGTERM
    at C:\Users\louis\AppData\Roaming\nvm\v14.21.3\node_modules\katalon-recorder-cli\node_modules\selenium-webdriver\remote\index.js:259:24
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:9708) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by LemassonLouis** [comment]
Hi, have you some news about this ?
